src/mkdocstrings/documenter.py
Due to some ungrouped logical statements, the first pair (`j < len(lines) and lines[j].startswith("    ")`) was getting skipped and the `or` was getting evaluated: `lines[j] == ""`, resulting in an `IndexError` when the admonition is at the end of the docstring:
```py
"""
Returns:
return_value: Return value description
TODO:
Write better docs.
"""
```
```py
File ".../lib/python3.6/site-packages/mkdocstrings/documenter.py", line 334, in parse_docstring
while j < len(lines) and lines[j].startswith("    ") or lines[j] == "":
IndexError: list index out of range
```
This groups it so that checks on `lines[j]` only happen if `j` is in fact less than `len(lines)`, and thus, in range.
=> Fix IndexError in Admonitions loop

src/mkdocstrings/documenter.py
Optional params will always [follow the pattern](https://docs.python.org/3/library/typing.html#typing.Optional) `Union[X, NoneType]`, so we can match on it and give a more succinct type string.
Also, I saw the vistigial code for default params, so I figured I'd work it back in, using `*required*` as a stand-in for params without a default value.
=> Document Optional and Default params

src/mkdocstrings/plugin.py
I have some `---` lines in my docstrings for better separation, and it broke the check for heading level. I realize this is brittle and subject to change, but in the meantime, figured I'd submit a fix.
=> Check if `<h` line is numeric, fixes breakage on `<hr>` lines

scripts/gen-credits-data.py, scripts/templates/CREDITS.md, scripts/templates/vlz/Jinja2.txt, scripts/templates/vlz/commonmark.txt, src/mkdocstrings/documenter.py, src/mkdocstrings/plugin.py
This PR does a refactor of the code to make it more readable and robust.
We removed the "categories" and re-implemented them using subclasses of `Object`.
This PR also adds a feature: the signature (or type annotation) for attributes.
The next commits will refactor the functions related to signatures and parameters.
=> WIP: refactor: Use Object subclasses

src/mkdocstrings/documenter.py
To know if we must discard the docstring,
we check in every parent classes for the same
special member, and if it exists and is equal
to the current docstring, we discard the docstring.
=> fix: Fix discarding docstring

src/mkdocstrings/docstrings.py
My docstring:
```
Args:
read_response: Block and read response. If there is a separate thread running,
this can be false, and the reading thread can read the output.
```
(it should have had an indent at `this`)
mkdocstrings out put (Before):
```
INFO    -  Building documentation... 
[E 200125 14:38:21 ioloop:909] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
Traceback (most recent call last):
File "/home/csmith/git/pygdbmi/.nox/serve_docs/lib/python3.6/site-packages/tornado/ioloop.py", line 907, in _run
return self.callback()
File "/home/csmith/git/pygdbmi/.nox/serve_docs/lib/python3.6/site-packages/livereload/handlers.py", line 69, in poll_tasks
filepath, delay = cls.watcher.examine()
File …
```
=> handle unparsable line more nicely

README.md, src/mkdocstrings/docstrings.py, src/mkdocstrings/documenter.py
Fix 1:
The signature cannot be determined from this code.
```
class MyError(ValueError):
"""Raise when trying to ..."""
pass
```
This PR uses an empty signature when signature cannot be determined. 
Fix 2:
When a docstring for arguments has a type hint, an error would be thrown. This PR strips out text in parentheses from the argument name, and allows documentation to be successfully generated.
(Unfortunately I do not have the time to write full tests for these fixes, but wanted to share them anyway)
=> handle types in docstring args, Exception types

src/mkdocstrings/docstrings.py, src/mkdocstrings/renderer.py, src/mkdocstrings/utils.py
If there is no type associated with an argument, display an empty table cell rather than the word `_empty`.
fixes #34
=> do not render empty types

src/mkdocstrings/plugin.py
Temporary workaround to prevent numpy from being reloaded when live watching locally.
See issue raised at https://github.com/pawamoy/mkdocstrings/issues/36#issuecomment-594495481 for more details.
=> Do not reload numpy

src/mkdocstrings/handlers/python.py
Signed-off-by: Reece Dunham <me@rdil.rocks>
The plan is that this should fix `python` not being properly resolved, and maybe help out with #91
=> Use the proper python executable to start subprocesses

src/mkdocstrings/plugin.py
This PR adds support for mkdocs-material's custom_dir configuration, where theme `name` is set to null in mkdocs.yaml. Thereby,  it adds support to automatically read out the required theme_name from `dirs` attribute, only if `name` attribute is None(or null), otherwise default behaviour will occur.
Fixes #120.
=> fix: mkdocstrings unable to parse custom theme directory configuration

CREDITS.md, src/mkdocstrings/handlers/python.py, src/mkdocstrings/templates/python/material/attribute.html, src/mkdocstrings/templates/python/material/class.html, src/mkdocstrings/templates/python/material/function.html, src/mkdocstrings/templates/python/material/method.html, src/mkdocstrings/templates/python/material/module.html
Implements the Python handler option `show_root_members_full_path`:
Shows the full Python path of the direct children of the object at the
root of the documentation tree. Defaults to false.
References #134
=> feat (python handler): Root children full path

src/mkdocstrings/handlers/python.py
Closes #154
I'm not sure if this is what we want, or if we want to _not_ pass `**config` in the parent `get_handler()` implementation, but either of these should resolve the bug showcased in #154.
https://github.com/florimondmanca/mkdocstrings/blob/25373148699daad42b319fa04213d405ca8a7c4c/src/mkdocstrings/handlers/__init__.py#L244
---
PS: I wasn't able to run `make setup` (I don't have 3.6 and 3.7 installed, and pinning `PYTHON_VERSIONS = ("3.8",)` results in a strange error I couldn't find the cause of…
```console
$ make setup
Setting up Python 3.8 environment
---------------------------------
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
NameError: name 'PosixPath' is not defined
make: *** [setup] Error 1
```
=> Bring back arbitrary **config to Python handler

src/mkdocstrings/extension.py
The current character set currently seems tailored to the Python handler, but can be not enough for others
(example identifier for a planned Crystal handler: `Foo::Type#bar(a,b)`)
And it doesn't seem like there's any strong reason to limit these?
=> feat: Allow any characters in identifiers

docs/usage.md, src/mkdocstrings/extension.py
This also refactors the regex to use the `MULTILINE` flag instead of the complex "manual" alternative for detecting newlines.
=> feat: Allow specifying heading_level as a Markdown heading instead

CREDITS.md, pyproject.toml, src/mkdocstrings/extension.py, src/mkdocstrings/references.py, tests/fixtures/cross_reference.py, tests/test_extension.py, tests/test_references.py
Define a "transport representation" for autorefs:
```html
<span data-mkdocstrings-identifier="SomeIdentifier">SomeHTML</span>
```
First a native Markdown extension translates from the usual `[SomeMarkdown][SomeIdentifier]` to the above, and then the post-process replacement mechanism (which is kept in the same place as before) doesn't need to be so careful and complicated, it just indiscriminately replaces such exact strings.
This is a very big boost in performance and I think is more future-proof.
Other mkdocstrings handlers are also free to use this mechanism: define whatever syntax for autorefs that they need and then insert this exact HTML themselves, for the postprocessing to pick up later. It used to be possible to insert the square-brackets Markdown before, but that was very …
=> Rework autorefs replacement to not re-parse the final HTML

src/mkdocstrings/references.py, tests/test_references.py
If there's any xref inside docs/index.md, `url_a` ends up being '', and `url_a[-1]` fails.
=> fix: xreferences from the root index page

src/mkdocstrings/extension.py, src/mkdocstrings/handlers/base.py, src/mkdocstrings/plugin.py, tests/test_extension.py, tests/test_references.py
This makes `handlers_cache` no longer be global but instead be confined to the Plugin. There will be only one instance of the plugin so it doesn't matter anyway. But actually this is also more correct, because what if someone tried to instantiate multiple handlers with different configs? It would work incorrectly previously.
But my main goal for this is to expose `MkdocstringsPlugin.get_handler(name)`. Then someone can use this inside a mkdocs hook:
```python
def on_files(self, files: Files, config: Config):
docs = config['plugins']['mkdocstrings'].get_handler('python').collector
```
So this is basically a prerequisite for issue #179: one could query the collector to know which files to generate.
=> refactor: Split out the handler cache, expose it through the plugin

.github/workflows/ci.yml
GitHub actions are limited only to the branch that they are defined on anyway. So all this did was to prevent CI from running on a dev/feature branch
=> Don't limit CI runs to just master branch

src/mkdocstrings/references.py
First introduced in https://github.com/pawamoy/mkdocstrings/pull/188, there's a regression: if something messes with the final HTML before mkdocstrings plugin gets to it, it can't be detected and replaced.
A known case is with 'minify' plugin if it appears before our plugin in the config (which it shouldn't anyway).
So workaround this specific case. Make the attribute quotes optional to also catch minified HTML.
Hard to do much else, though perhaps a warning would make sense.
=> fix: More lenient regex for data-mkdocstrings-identifier

src/mkdocstrings/handlers/base.py, src/mkdocstrings/templates/python/material/attribute.html, src/mkdocstrings/templates/python/material/attributes.html, src/mkdocstrings/templates/python/material/class.html, src/mkdocstrings/templates/python/material/docstring.html, src/mkdocstrings/templates/python/material/examples.html, src/mkdocstrings/templates/python/material/exceptions.html, src/mkdocstrings/templates/python/material/function.html, src/mkdocstrings/templates/python/material/method.html, src/mkdocstrings/templates/python/material/module.html, src/mkdocstrings/templates/python/material/parameters.html, src/mkdocstrings/templates/python/material/return.html, src/mkdocstrings/templates/python/readthedocs/exceptions.html, src/mkdocstrings/templates/python/readthedocs/parameters.html, src/mkdocstrings/templates/python/readthedocs/return.html
Fixes #193
https://github.com/pawamoy/mkdocstrings/issues/193#issuecomment-749134463
Fixes #186 
https://github.com/pawamoy/mkdocstrings/issues/186#issuecomment-743469671
=> Make ids of Markdown sub-documents prefixed with the parent item id

src/mkdocstrings/handlers/base.py
Any time a template is referenced, even though it's cached in memory, Jinja ends up doing a filesystem access, to check whether the template file has been modified and so would need to be recompiled.
But it's not even useful to be able to modify a template file on disk in the middle of a mkdocs build.
[An equivalent change to MkDocs itself proved to improve performance significantly](https://github.com/mkdocs/mkdocs/pull/2261). I can't say the same about mkdocstrings, as its templates aren't as nested, but it'll still help. And just good for consistency now.
=> Disable Jinja's auto_reload, to reduce disk reads

src/mkdocstrings/extension.py
The follow-up calls for each block make no difference at all, and are getting quite expensive.
=> perf: Call `update_env` only once per `Markdown` instance

src/mkdocstrings/extension.py
I conclude that it's unused because the condition necessarily requires finding something with class 'autodoc' -- but there is nothing that creates anything with class 'autodoc'!
=> refactor: remove some unused code

src/mkdocstrings/extension.py, tests/test_extension.py
```markdown
foo
**foo**
::: some.identifier
```
In the previous state, the "foo" text would be completely obliterated, but now it will be kept, and the autodoc will be rendered as well.
=> fix: Don't wrongly discard text immediately before an autodoc

tests/test_extension.py
This fixes random test failures that for some reason showed up only on Windows Python 3.6
=> tests: Run teardown for Handlers, refactor into contextmanager

src/mkdocstrings/handlers/base.py, tests/test_extension.py
This was a regression from https://github.com/pawamoy/mkdocstrings/pull/203.
This ended up disabling permalinks outright for all docs.
=> fix: Don't mutate the original Markdown config for permalinks

docs/css/mkdocstrings.css, docs/handlers/python.md, pyproject.toml, src/mkdocstrings/extension.py, src/mkdocstrings/handlers/base.py, src/mkdocstrings/references.py, src/mkdocstrings/templates/python/material/attribute.html, src/mkdocstrings/templates/python/material/children.html, src/mkdocstrings/templates/python/material/class.html, src/mkdocstrings/templates/python/material/function.html, src/mkdocstrings/templates/python/material/method.html, src/mkdocstrings/templates/python/material/module.html, tests/fixtures/builtin.py, tests/test_extension.py
* ## refactor: Merge md extensions into one, to reduce boilerplate
* ## refactor: Pass the actual used Markdown instance to update_env
The fact that we're re-instantiating Markdown used to be seen as a hack, but now it's required and preferred.
* ## refactor: Move do_convert_markdown method into the class
* ## refactor: Don't re-parse the whole subdoc, expose only headings
Previously the autodoc sub-document (HTML with nested Markdown) was being re-integrated into the top-level document by the way of parsing it as XML and inserting it back into the XML tree of the top-level markdown duri>
This gave a lot of side effects that need to be worked around. XML parsing, Markdown double-processing (with only situational workaround possible), etc.
Now, the document will be inserted as fully opaque …
=> refactor: Don't re-parse the whole subdoc, expose only headings

docs/css/mkdocstrings.css, docs/handlers/overview.md, docs/handlers/python.md, src/mkdocstrings/handlers/base.py, src/mkdocstrings/plugin.py, src/mkdocstrings/templates/python/material/style.css, src/mkdocstrings/templates/python/readthedocs/style.css
=> feat: Let handlers add CSS to the pages, do so for Python handler

src/mkdocstrings/handlers/base.py, src/mkdocstrings/templates/python/material/attribute.html, src/mkdocstrings/templates/python/material/class.html, src/mkdocstrings/templates/python/material/examples.html, src/mkdocstrings/templates/python/material/function.html, src/mkdocstrings/templates/python/material/method.html, src/mkdocstrings/templates/python/material/signature.html, tests/test_handlers.py
Infer the highlighter configs from what the current Markdown config is, trying to mimick the two most typical extensions and how they'd highlight a code block in Markdown normally.
This improves theme support, as previously only some assumptions based on each theme's defaults were supported, e.g. the readthedocs theme is assumed to rely only on JS highlighting, when in reality you just need to add a Markdown syntax highlight extension and you can use Pygments.
I had commented on this here: https://github.com/pawamoy/mkdocstrings/pull/159#discussion_r502792729
Another improvement stemming from this is support for disabling syntax highlighting altogether. (`use_pygments: false`). For that I also had to edit the template for function signature, to avoid all newlines in it, because previously …
=> refactor: Theme-agnostic code highlighting, respecting configs

src/mkdocs_autorefs/plugin.py, src/mkdocstrings/extension.py, src/mkdocstrings/handlers/python.py
(though definitely not nicer-looking in terms of code)
The important thing I want to address is actually a kind of regression from https://github.com/pawamoy/mkdocstrings/pull/217: now `collect()` can be called from an "implicit" operation such as generating an cross-reference, and even though errors in that operation are suppressed, the explicit `log.error()` inside `collect()` is not suppressed, so I just fold that into the exception message.
<details><summary>Output for missing reference on 0.14.0</summary>
```
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
WARNING -  mkdocstrings.plugin: handlers/overview.md: Could not find cross-reference target '[mkdocsatrings.handlers.base.BaseHandler]' 
```
</details>
<details><summary>Output for missing reference on …
=> feat: Nicer error outputs - no tracebacks from mkdocstrings

.github/ISSUE_TEMPLATE/question.md, CHANGELOG.md, README.md, docs/css/mkdocstrings.css, docs/css/style.css, docs/handlers/overview.md, docs/handlers/python.md, docs/theming.md, docs/troubleshooting.md, docs/usage.md, mkdocs.yml, pyproject.toml
* Document more about autorefs, warn about the breaking change.
* Linkify *Features* on the home page.
* Mention Crystal handler (+add CSS for external link).
* Split out a "theming" page from "usage" page.
* Linkify sections via *mkdocs-section-index* plugin.
* Update links after the site has moved into an org.
* Indent some examples into an admonition.
* Change "`mkdocstrings`" and "MkDocstrings" to "*mkdocstrings*".
* Some minor rewordings.
=> docs: Details about autorefs, reorganize nav, update links & more

config/flake8.ini, duties.py, pyproject.toml, tests/test_extension.py, tests/test_plugin.py
Flakehell is abandoned, I personally ran into problems with its faulty lingering cache, and now it's preventing me from configuring darglint.
This was causing random test failures because multiple tests concurrently try to delete and re-create the same site dir.
Refactor to use pytest fixtures instead while on it.
Bonus: allow docstrings to not specify Arguments sections etc. But if they are specified, they will still be checked.
Here because it's ridiculous to document fixtures in every test function. Generally because sometimes all args are obvious if it's just an override.
=> tests: Build test sites into a temp directory

src/mkdocstrings/handlers/rendering.py, tests/fixtures/string_annotation.py, tests/test_extension.py
=> fix: Don't double-escape characters in highlighted headings

src/mkdocstrings/handlers/python.py
There seems to be no problem in propagating the `stderr` outwards, and without this there is no feedback as to what went wrong in the `step_commands`.
=> allow printing collector process stderr to system

src/mkdocstrings/handlers/base.py, tests/test_extension.py
Custom handlers configured in individual
autodoc instructions were not picked up
by mkdocstrings.
Issue #259
=> fix: Fix custom handler not being used

src/mkdocstrings/templates/python/material/attributes.html, src/mkdocstrings/templates/python/material/parameters.html, src/mkdocstrings/templates/python/material/return.html, src/mkdocstrings/templates/python/mkdocs/exceptions.html, src/mkdocstrings/templates/python/mkdocs/parameters.html, src/mkdocstrings/templates/python/mkdocs/return.html, src/mkdocstrings/templates/python/mkdocs/style.css, src/mkdocstrings/templates/python/readthedocs/parameters.html, src/mkdocstrings/templates/python/readthedocs/return.html
*    fix: Don't render empty code blocks for missing type annotations
*    feat: Very basic support for MkDocs theme
It mimicks the look and the elements applied on this page: https://www.mkdocs.org/user-guide/plugins/
=> feat: Very basic support for MkDocs theme

docs/handlers/python.md
=> docs: Add docstring style configuration instructions in 'Supported styles' section

pyproject.toml
and same for MarkupSafe.
They mainly just drop Python 2.
* https://jinja.palletsprojects.com/en/master/changes/#version-3-0-0
* https://markupsafe.palletsprojects.com/en/master/changes/#version-2-0-0
=> build: Looks like we're ready for the upcoming major Jinja release

src/mkdocstrings/plugin.py
Example of how an external handler can be implemented:
* https://github.com/mkdocstrings/crystal/compare/inv#commit_comments_bucket
* ```yaml
plugins:
- mkdocstrings:
handlers:
crystal:
import:
- https://crystal-lang.org/api/latest/index.json
```
Alternative to https://github.com/mkdocstrings/autorefs/pull/4
=> feat: Support loading external inventories and linking to them

src/mkdocstrings/handlers/python.py, src/mkdocstrings/inventory.py, src/mkdocstrings/plugin.py
\+ small refactors in InventoryItem
Completely random example of how this is used:
```diff
diff --git a/docs/usage.md b/docs/usage.md
index ce8c0bef7..9c69459bd 100644
--- a/docs/usage.md
+++ b/docs/usage.md
@@ -1,3 +1,5 @@
+[github.Topic.Topic.created_at][]
+
diff --git a/mkdocs.yml b/mkdocs.yml
index f3cbe2778..9d40b3108 100644
--- a/mkdocs.yml
+++ b/mkdocs.yml
@@ -46,5 +46,7 @@ plugins:
- sys.path.append("docs")
selection:
new_path_syntax: yes
+        import:
+        - https://pygithub.readthedocs.io/en/latest/objects.inv
watch:
- src/mkdocstrings
```
=> feat: Support loading external Python inventories in Sphinx format

pyproject.toml, src/mkdocstrings/handlers/python.py, src/mkdocstrings/templates/python/material/class.html
I'm not sure if this is the best way to present them, or if it should be on by default.  Feedback welcome.
Fixes https://github.com/mkdocstrings/mkdocstrings/issues/269
Requires https://github.com/mkdocstrings/pytkdocs/pull/108
Best with https://github.com/mkdocstrings/autorefs/pull/10 so that you can hover over a base class to see the fully qualified name
Screenshot:
=> Optionally show base classes

docs/reference/autorefs/plugin.md, src/mkdocstrings/handlers/python.py, src/mkdocstrings/templates/python/material/children.html, tests/test_python_handler.py
Hey! I developed this feature for my own use but figured it could be useful for others too. I wanted to make the members of a class appear as they do in the source file, instead of sorting them alphabetically. So I added this option. It works like:
```yaml
::: mkdocs_autorefs.plugin
rendering:
sort_members: source
```
'lexical' is the default, 'source' sets the order to that in the source file. It works by pulling the sort behaviour out of the template, and into the PythonRenderer.
This might be related to #102? Or maybe not.
=> feat: Add a rendering option to change the sorting of members

src/mkdocstrings/templates/python/material/class.html
This happens when pytkdocs is not in version 0.12.
This change therefore supports versions before 0.12.
=> refactor: Don't add parentheses when class has no bases

pyproject.toml, src/mkdocstrings/extension.py, src/mkdocstrings/handlers/base.py, src/mkdocstrings/handlers/python.py, src/mkdocstrings/plugin.py
Since an object can have aliases (different identifiers
leading to it), and since users sometimes want to
render an object using one of its aliases instead of its
canonical identifier, we make sure to register every
identifier associated to an object so that autorefs
can find it when fixing cross-references.
Issue mkdocstrings/autorefs#11
Needs PR https://github.com/mkdocstrings/autorefs/pull/12
=> refactor: Return multiple identifiers from fallback method

src/mkdocstrings/templates/python/material/docstring.html, src/mkdocstrings/templates/python/material/keyword_args.html, src/mkdocstrings/templates/python/material/yield.html, src/mkdocstrings/templates/python/mkdocs/keyword_args.html, src/mkdocstrings/templates/python/mkdocs/yield.html, src/mkdocstrings/templates/python/readthedocs/keyword_args.html, src/mkdocstrings/templates/python/readthedocs/yield.html
=> Support keyword args and yields sections

src/mkdocstrings/loggers.py
Instead of prefixing logs with `mkdocstrings.extension: ` or `mkdocstrings.plugin: ` we prefix them with just `mkdocstrings: `.
I don't think it's useful to log the full module path (easy to know where the log comes from).
I'm trying to standardize a bit more logging from plugins :slightly_smiling_face:
=> refactor: Prefix logs with the package name only

pyproject.toml
I just pushed new versions of both Python handlers to make sure they depend on `mkdocstrings>=0.18`, and so updated the extras here.
I've also added the `crystal` extra.
=> build: Update extras

docs/handlers/overview.md
Just a small update to the documentation, pointing out that docstring options are available now under the experimental python handler. :)
=> docs: Update note about supported docstring options

src/mkdocstrings/extension.py, src/mkdocstrings/handlers/base.py, src/mkdocstrings/plugin.py, tests/test_extension.py
Commit message:
The BaseCollector and BaseRenderer are merged into
the BaseHandler (as mixins for now).
Developers are still able to create collectors
and renderers using these deprecated base classes,
and pass instances of them when creating their handler.
All the methods of the deprecated bases can now
be defined on the BaseHandler subclass itself.
Handlers can then be instantiated by passing
the handler's name, the theme and the optional
custom templates folder name/path.
Reasoning: often times, the renderer and the collector
need to communicate or share data. For example,
the Crystal renderer uses the collector to lookup names
when creating cross-references. The Python handlers
are able to filter members when collecting/returning data,
and need the same members list when rendering,
to …
=> refactor: Deprecate BaseCollector and BaseRenderer

mkdocs.yml, src/mkdocstrings/extension.py, tests/test_extension.py
Commit message:
As seen in commit eb822cb, the separation of
the selection/collection and rendering configuration
is problematic. This commit further reduces this
separation by merging the two current YAML keys
'selection' and 'rendering' into a single
'options' key. It means both the 'collect' and
'render' methods have access to every option.
The old keys can still be used, but are deprecated,
and therefore a deprecation warning is emitted
if these keys are found in either global or local
configurations.
---
This was mentioned in #364.
Example diffs:
```diff
plugins:
- mkdocstrings:
handlers:
python:
-        selection:
+        options:
docstring_style: google
docstring_options:
ignore_init_summary: yes
-        rendering:
merge_init_into_class: yes
show_submodules: no
```
```diff
::: …
```
=> refactor: Deprecate 'selection' and 'rendering' YAML keys

src/mkdocstrings/handlers/base.py, src/mkdocstrings/plugin.py
This is to allow handlers to build potential paths
(like Python search paths) relative to the MkDocs
configuration file path instead of the current
working directory. Without it, the build becomes
dependent on the CWD, breaking the --config-file
option.
Issue #311
=> feat: Pass config file path to handlers

docs/gen_ref_nav.py, docs/recipes.md, mkdocs.yml
Been going crazy about this for the last couple of hours and unable to figure out for my personal docs and saw that this behaviour was also reproducible in the repo. Eventually found it and it is caused by the use of [urllib.parse.urljoin](https://github.com/oprypin/mkdocs-gen-files/blob/master/mkdocs_gen_files/plugin.py#L49-L51) in the gen_files plugin, which misinterprets the links if they are not ended in `/` (@oprypin would you rather this gets fixed there instead?)
Additionally, I noticed that the `edit_uri` makes the edit links for the now correct links have `docs/` as a base, which makes it link incorrectly, so I added a bit of a hacky fix to avoid that
An example of the now broken page links can be seen [here](https://mkdocstrings.github.io/reference/extension/), where clicking on …
=> Fix edit link for autogenerated docs

src/mkdocstrings/extension.py, src/mkdocstrings/plugin.py, tests/test_extension.py
The other warnings are developer-facing and should indeed remain as DeprecationWarning.
=> refactor: Report usage-based warnings as user-facing messages

src/mkdocstrings/extension.py, src/mkdocstrings/loggers.py, src/mkdocstrings/plugin.py
Also for event type annotations - if, hypothetically, MkDocs started to support them.
=> refactor: Small fixes to type annotations

docs/usage.md
A small PR to (in my opinion) improve the clarity of the `custom_templates` config option.  
The reason for this is that when I read the current line:
> the path to a directory containing custom templates. The path is relative to the docs directory
I assumed it meant it was relative to **within** the docs directory. 
Only after looking up other repositories with examples I noticed that you have to include `docs` in the path if your templates are in that folder.
This is not meant to be final, just an example. If this is not the place for the explanation, I don't mind moving it either.
=> docs: Clarify `custom_templates` folder location in options documentation

src/mkdocstrings/inventory.py
As mentioned in #496, some Sphinx inventories don't match the `sphinx_item_regex` defined in `InventoryItem`. Allowing any number of whitespace characters at the end instead of requiring at least one fixes this issue.
Fixes #496.
=> fix: Fix broken Sphinx inventory item regex

docs/usage.md, src/mkdocstrings/plugin.py, tests/test_plugin.py
Fixes #478.
For the docs entry I guessed that it will be released in version 0.20, this might have to be adjusted.
I considered adding a test but I couldn't see some obvious way to extend the test suite.
=> feat: add plugin `enabled` config option

src/mkdocstrings/extension.py, src/mkdocstrings/handlers/base.py
Didn't want to take the full performance hit of doing it every time, so it now tracks if this autodoc instance has seen this handler before and if not; updates the handler's env.
Additionally, add a doc string to `_update_env` just a breadcrumb.
References: #201
Fixes: #502
---
I had issues with the instructions in `contributing.md` and had to manually install pdm on both windows/osx.  I got format working but check_types and test failed in locations not associated with this change.
=> fix:  handle multiple handler's envs on same the doc

README.md, docs/recipes.md, docs/theming.md, docs/usage.md, src/mkdocstrings/extension.py, src/mkdocstrings/handlers/base.py
Just a minor change to the Quick Usage example in the README, so that it runs as-is. (`mkdocs` complains about no `site_name` defined otherwise).
---
EDIT 2023-01-26: and a few other typos / docs clarification.
=> docs: complete example for quick usage

README.md
I'm just getting started. I use Python fairly frequently but am not a tooling expert and don't know a lot about package naming conventions. Here was my journey:
- First I copied `pip install mkdocstrings[crystal,python]` exactly and that didn't work.
- Then I figured maybe `[crystal,python]` was intended as some kind of disjunction notation so I tried `mkdocstringpython` and that didn't work.
- Then I followed the link to https://mkdocstrings.github.io/handlers/overview/ and didn't see anything about pip installation.
- Then I clicked on the experimental link and made my way to https://mkdocstrings.github.io/python/
- Then I saw `mkdocstrings-python` in the PEP 621 declaration and tried `pip install mkdocstrings-python`
That feels like a lot of unnecessary friction! I think the clearest …
=> Update language extras install examples with pip

pyproject.toml, src/mkdocstrings/handlers/base.py
This is needed by python library because `collect()` needs to pass that argument to a method that declares it as MutableMapping.
=> fix: correct type signature for BaseCollector.collect

docs/handlers/overview.md, src/mkdocstrings/handlers/base.py, src/mkdocstrings/plugin.py
Instead of just passing only the handler_config on initialization pass the full dictionary of `extension_config` directly to the handler.  Refactors items that were pulled from the full configuration to point directly to that object.
References: #501
=> feat: expose the full config to handlers

docs/usage/handlers.md, pyproject.toml, src/mkdocstrings/handlers/base.py, tests/test_handlers.py
An extension here is simply a Python package that defines an entry-point for a specific handler.
For example, an extension can add templates to the Python handler thanks to this entry-point:
```toml
[project.entry-points."mkdocstrings.python.templates"]
extension-name = "extension_package:get_templates_path"
```
This entry-point assumes that the extension provides a `get_templates_path` function directly under the `extension_package` package. This function doesn't accept any argument and returns the path to a directory containing templates. The directory must contain one subfolder for each supported theme, for example:
```
templates/
material/
readthedocs/
mkdocs/
```
mkdocstrings will add the folders corresponding to the user-selected theme, and to the handler's defined fallback theme, …
=> feat: Allow extensions to add templates

docs/troubleshooting.md
I added a note about new-line handling. Maybe its a bug that I should be reporting elsewhere?
```python
class ExampleClass:
"""This class is broken because of \n
Example:
```python
msg = "There should be a newline char at the end of this example\n"
print(msg)
```
"""
pass
```
produces this:
> ![image](https://github.com/mkdocstrings/mkdocstrings/assets/57631333/3ae8d7ca-5308-469d-a2b8-cc3e3bc0e517)
Escaping the "\n" with an additional "\" produces:
> ![image](https://github.com/mkdocstrings/mkdocstrings/assets/57631333/49f957a6-1c6c-490d-b4b2-a7f827d39044)
my mkdocs.yaml:
```mkdocs
markdown_extensions:
- admonition
- codehilite
- pymdownx.superfences
plugins:
- search
- mkdocstrings:
handlers:
python:
options:
docstring_style: "google"
=> Add note about newline handling

config/mypy.ini, config/ruff.toml, docs/usage/handlers.md, docs/usage/index.md, pyproject.toml, src/mkdocstrings/__init__.py, src/mkdocstrings/extension.py, src/mkdocstrings/handlers/__init__.py, src/mkdocstrings/handlers/base.py, src/mkdocstrings/plugin.py, tests/test_extension.py
Removed:
- Base collector class
- Base renderer class
- Watch feature
- Selection and rendering keys support (YAML options)
- `mkdocstrings.handlers` namespace (when importing handlers and finding templates)
=> refactor: Remove deprecated parts

src/mkdocstrings/extension.py, tests/test_extension.py
Hi,
As mentioned in #609, nesting a docstring in another block (e.g., tab or admonition) produces duplicated headings.
At the moment, the extension postprocessor only checks inside the immediate root children when removing duplicated heading.
Some markdown extensions move the produced docstring in a nested html node : we only need to search deeply when removing duplicatas.
=> Remove duplicated headings for docstrings nested in tabs/admonitions

src/mkdocstrings/extension.py, tests/fixtures/headings_many.py, tests/test_extension.py
In the newly added test these were failing in the previous state:
* `assert output.count(">Heading one<") == 1` - [**comment**](https://github.com/mkdocstrings/mkdocstrings/pull/610/files/d0f06d4b80765ce2e6b8e27fb410439506cc318c#r1328531524)
* `assert output.count(">Heading two<") == 1` - [**comment**](https://github.com/mkdocstrings/mkdocstrings/pull/610/files/d0f06d4b80765ce2e6b8e27fb410439506cc318c#r1328530389)
And delete unused boolean
=> fix: Properly fix duplicated headings for nested docstrings

CHANGELOG.md, docs/usage/index.md, docs/usage/theming.md, src/mkdocstrings/plugin.py, tests/test_plugin.py
Fixes #477.
I have not even looked at tests, etc. But this should be working code.
=> Make custom_templates relative to config file

docs/recipes.md
always use tuple(), as in the second example
=> be consistent in examples

README.md
Hi,
Currently navigating to https://mkdocs.org/ causes a certification error.
Changing the link to https://www.mkdocs.org/ circumvents this.
=> Circumvent error with mkdocs link.

src/mkdocstrings/handlers/rendering.py, tests/fixtures/markdown_anchors.py, tests/test_extension.py
This will be useful for the soon-to-come Markdown anchors feature of mkdocs-autorefs.
Related to mkdocs-autorefs#39: https://github.com/mkdocstrings/autorefs/pull/39
=> refactor: Backup anchors without hrefs, for compatibility with autorefs' Markdown anchors

README.md
I just encountered this today and it seems I'm at least the fourth person:
1. https://github.com/mkdocstrings/mkdocstrings/issues/648
2. https://github.com/mkdocstrings/mkdocstrings/issues/647
3. https://github.com/mkdocstrings/mkdocstrings/issues/623
This altered verbiage would have triggered me to correctly install mkdocstrings with support for Python.
=> Clarify that extras are *necessary* not optional

CONTRIBUTING.md
Closes https://github.com/mkdocstrings/mkdocstrings/issues/706.
Add instructions for pulling tags to ensure correct package version when building the project.
=> Update CONTRIBUTING.md to include tag pulling instructions

config/pytest.ini, src/mkdocstrings/extension.py, src/mkdocstrings/handlers/base.py, src/mkdocstrings/plugin.py
These changes straighten up what arguments are passed to the extension, the `Handlers` class, and the handlers' `get_handler` functions.
Previously there was a lot of redundancy, building and passing mutable dictionaries around.
Now we pass exactly what each class/function needs, as well as the global MkDocs config (renamed "tool config" to decouple ourselves a bit from MkDocs) in case users need it (`get_handler` functions and `update_env` methods, mainly).
These changes bring a few deprecations with relevant messages, as well as a few breaking changes in mkdocstrings' API for which we didn't identify any public use on GitHub.
- `mkdocstrings.extension.AutoDocProcessor.__init__(parser)`: *Parameter was removed*
- `mkdocstrings.extension.AutoDocProcessor.__init__(md)`: *Positional …
=> refactor: Clean up data passed down from plugin to extension and handlers

docs/troubleshooting.md
Updated a broken link for Arithmatex MathJax documentation to point to the correct URL.
=> docs: Fix a broken link

config/ruff.toml, scripts/insiders.py, src/mkdocstrings/_internal/handlers/base.py, src/mkdocstrings/_internal/inventory.py, tests/test_extension.py, tests/test_inventory.py
Hi! I'm Josh, I'm in charge of documentation at [Open Force Field](https://docs.openforcefield.org). We produce a particular kind of mathematical model for computational chemistry. I haven't been using mkdocs/mkdocstrings for long, but I'm enjoying getting to know it, and I'm very excited to write docstrings in markdown!
This is my first contribution here. Thanks for making such clear contributor docs! If you'd rather I do anything another way I'm very happy to fix things. Sorry I haven't raised an issue, but by the time I'd figured out what was going on I basically had the fix written, so it's all here.
When a display name in a Sphinx inventory file spans multiple lines, both mkdocstrings and Sphinx simply print the newline character and then the continuation. This is because a display …
=> fix: Load Sphinx inventories whose dispname spans multiple lines

src/mkdocstrings/_internal/extension.py, src/mkdocstrings/_internal/handlers/base.py
100% disclosure: I don't know why this works.
Resolves #796
=> fix: Create default ssl context and discard before downloading inventories
