.gitignore
src/mkdocstrings/__init__.py
src/mkdocstrings/extension.py
src/mkdocstrings/handlers/__init__.py
src/mkdocstrings/handlers/python.py
src/mkdocstrings/plugin.py

Signed-off-by: Reece Dunham <me@rdil.rocks>

Enhance some small things

---

.gitlab-ci.yml
Makefile
pyproject.toml
src/mkdocstrings/extension.py
src/mkdocstrings/plugin.py

To see if GitLab actually triggers a pipeline.

CI test PR check

---

src/mkdocstrings/extension.py
src/mkdocstrings/handlers/__init__.py
src/mkdocstrings/handlers/python.py
src/mkdocstrings/plugin.py

WIP: Add option to allow overriding of templates.

---

src/mkdocstrings/extension.py
src/mkdocstrings/handlers/__init__.py
src/mkdocstrings/handlers/python.py
src/mkdocstrings/plugin.py

Adds functionality described in #89

Initial PoC on running commands before processing

---

src/mkdocstrings/templates/python/material/docstring.html
src/mkdocstrings/templates/python/material/examples.html

This PR is to support the examples section.
In progress...
Issue https://github.com/pawamoy/pytkdocs/issues/8 and PR https://github.com/pawamoy/pytkdocs/pull/35

Support examples section

---

README.md

mkdocstrings is super useful so I added it to conda-forge to make it work with my workflow easier. Figured I'd add those install instructions to the README. Thanks!
I had to add pytkdocs as well since mkdocstrings depends on it.

Update README.md with conda install

---

pyproject.toml
src/mkdocstrings/loggers.py

I think this should fix the code quality error by flakehell. 👍

add flakehell exception to one file pyproject.toml

---

src/mkdocstrings/handlers/base.py
src/mkdocstrings/loggers.py

fix: Detecting paths relative to template directory in logging

---

src/mkdocstrings/references.py
tests/test_references.py

fix: error when a digit immediately follows a code tag

---

docs/handlers/python.md
src/mkdocstrings/handlers/base.py
src/mkdocstrings/templates/python/material/function.html
src/mkdocstrings/templates/python/material/method.html
src/mkdocstrings/templates/python/readthedocs/exceptions.html
src/mkdocstrings/templates/python/readthedocs/parameters.html
src/mkdocstrings/templates/python/readthedocs/return.html

Issue: https://github.com/pawamoy/mkdocstrings/issues/107

Add support for ReadTheDocs theme

---

src/mkdocstrings/templates/python/material/attribute.html
src/mkdocstrings/templates/python/material/class.html
src/mkdocstrings/templates/python/material/function.html
src/mkdocstrings/templates/python/material/method.html
src/mkdocstrings/templates/python/material/module.html

(there's no real issue with this but it's invalid and doesn't do anything)

fix: Remove strange 'href' from <h1..6>

---

src/mkdocstrings/templates/python/material/attribute.html

See https://github.com/pawamoy/mkdocstrings/pull/212#issuecomment-753656134

fix: Fix double code tags

---

.github/workflows/ci.yml

https://github.com/python-poetry/poetry/issues/3663

ci: Don't use Poetry debug mode, it's currently broken

---

duties.py
mkdocs.yml
src/mkdocstrings/extension.py
src/mkdocstrings/handlers/base.py
src/mkdocstrings/handlers/python.py
src/mkdocstrings/inventory.py
src/mkdocstrings/plugin.py
src/mkdocstrings/templates/python/material/attribute.html
src/mkdocstrings/templates/python/material/class.html
src/mkdocstrings/templates/python/material/function.html
src/mkdocstrings/templates/python/material/method.html
src/mkdocstrings/templates/python/material/module.html
tests/test_inventory.py

feat: Generate objects inventory

---

tests/test_extension.py

https://github.com/mkdocstrings/autorefs/pull/7

tests: Adapt to changes in the link syntax in mkdocs-autorefs

---

docs/troubleshooting.md

docs: Don't need the suggestion to upgrade Jinja if we ensure it

---

docs/handlers/python.md
docs/usage.md
mkdocs.yml
src/mkdocstrings/handlers/python.py
src/mkdocstrings/plugin.py

Not the best docs I've written, but it's a start.

Document loading and generating inventories

---

pyproject.toml

https://facelessuser.github.io/pymdown-extensions/about/changelog/#90

Support `pymdown-extensions` v9.x

---

README.md

Used the search to look for something useful, this looked like what was trying to be linked to.

Fix admonitions link in README

---

src/mkdocstrings/handlers/python.py
src/mkdocstrings/templates/python/material/signature.html

feat: Add `show_signature` rendering option

---

src/mkdocstrings/handlers/base.py

Namespace packages can be installed into multiple locations (and not merged into a single one).
To find the right templates directory, we must therefore find the right handler path.

feat: Support handlers spanning multiple locations

---

src/mkdocstrings/handlers/base.py
src/mkdocstrings/handlers/rendering.py

feat: Allow unwrapping the `<p>` tag in `convert_markdown` filter

---

src/mkdocstrings/loggers.py

Prepare for jinja2 3 1

---

README.md

@oprypin did you have something else in mind?

docs: Add obvious link to our Gitter channel

---

docs/recipes.md

Fix Windows support for automatic code reference pages

---

CONTRIBUTING.md
docs/handlers/overview.md
docs/recipes.md
docs/theming.md
docs/troubleshooting.md
docs/usage.md
mkdocs.yml
pyproject.toml
src/mkdocstrings/plugin.py

Hey @oprypin (and other watchers), I've updated the docs for the upcoming version (0.19).
I'll add comments on interesting points.

docs: Update docs

---

CONTRIBUTING.md

I am making this contribution just to avoid depending on a approval on every push I make on #511
Once it gets it, GHA should no longer ask for approval. Still, I do find these fixed as a minor improvement anyway.

Few grammar fixes

---

src/mkdocstrings/plugin.py

This change should enable us to pass any kind of configuration arguments to the inventory
and unblock https://github.com/mkdocstrings/python/pull/49 which was not able to load
sequences as PYYAML loads them as lists, which are mutable and not allowed by pycache.
As this method is not expected to modify any of the received data, there is no problem to
convert its non-mutable list arguments into tuples using a small wrapper.
Partial: https://github.com/mkdocstrings/mkdocstrings/issues/510

Make _load_inventory accept lists as arguments

---

src/mkdocstrings/plugin.py

refactor: Report inventory loading errors

---

docs/recipes.md

docs: Make recipe work with MkDocs `-f` option

---

docs/recipes.md

The code highlight lines appeared to be incorrect. This pull request resolves the issue.

docs: Update code highlight lines

---

pyproject.toml
src/mkdocstrings/_internal/extension.py
src/mkdocstrings/_internal/handlers/base.py
src/mkdocstrings/_internal/plugin.py

feat: Backlinks

---

README.md
docs/usage/handlers.md
mkdocs.yml

Hi @pawamoy 👋
I've got another handler here :)

docs: add links to GitHub Actions handler
